version: "3.8"
services:

  app:
    build:      
      context: ./
      dockerfile: Dockerfile
    image: aurora-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db:/var/lib/mysql

  web:
    image: nginx:alpine    
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
